// tables/tables-ocean.js

export const tables = {
    thematic_modules: [
        {
            title: "When The Lighthouse Lies",
            intro: "A distant beacon burns brightly, but there’s nothing on any of the charts and maps...",
            details: 'The first to spot it is ${Ocean.sub_tables.lighthouse_lies_spotter}. The lighthouse may actually be ${Ocean.sub_tables.lighthouse_lies_actual}. The superstitious crew takes this as an omen of ${Ocean.sub_tables.lighthouse_lies_omen}.'
        },
        {
            title: "The Lifeboat",
            intro: "Slightly off starboard bobs a boat full of seven sailors...",
            details: 'The sailors have been adrift ${Ocean.sub_tables.lifeboat_adrift}. Their ship ${Ocean.sub_tables.lifeboat_ship}. Aboard their craft, they also carry ${Ocean.sub_tables.lifeboat_carry}.'
        },
        {
            title: "A Sea Of Storms",
            intro: "They say that the Brine Queen’s suitor, the Storm God, paints the sky red in the mornings before he comes a courting....",
            details: 'Other ways the weather is predicted in these parts include ${Ocean.sub_tables.sea_of_storms_prediction}. This particular storm is likely to last ${Ocean.sub_tables.sea_of_storms_duration}. In addition to the typic perils, this Storm could ${Ocean.sub_tables.sea_of_storms_perils}.'
        },
        {
            title: "Pirates",
            intro: "Your ship may not be the only vessel to ply these lanes, as a peer at a distant blot through the Captain’s lookstick reveals...",
            details: 'The pirates ${Ocean.sub_tables.pirates_crew}. At this very moment, ${Ocean.sub_tables.pirates_moment}. Their Captain ${Ocean.sub_tables.pirates_captain}.'
        },
        {
            title: "Krakenspawn",
            intro: "The ship grinds and groans to a halt as fleshy mauve arms snake and ripple through the rails...",
            details: 'By counting tentacles, the best estimation of their number is ${Ocean.sub_tables.krakenspawn_number}. It is said that their beaks ${Ocean.sub_tables.krakenspawn_beaks} and their tentacles ${Ocean.sub_tables.krakenspawn_tentacles}. As if their writhing tenacity wasn’t enough, Krakenspawn ${Ocean.sub_tables.krakenspawn_tenacity}.'
        },
        {
            title: "The Drying",
            intro: "Your ship rests unsteadily atop a thick layer of seabed muck. The sea here has suddenly retreated for miles in all directions.",
            details: 'The sea’s retreat may only last ${Ocean.sub_tables.drying_duration}. The prevailing theory on how this is caused is ${Ocean.sub_tables.drying_theory}. Your predicament is not likely to go unnoticed for long by ${Ocean.sub_tables.drying_predicament}.'
        },
        {
            title: "The Whitecap Wizard",
            intro: "Seated at the bow of a small, ornately decorated boat is a hunched figure who’s long beard whips about in the wind...",
            details: 'Whitecap Wizards ${Ocean.sub_tables.whitecap_wizard_wizards}. His companion ${Ocean.sub_tables.whitecap_wizard_companion}. For a modest fee, he will begrudgingly ${Ocean.sub_tables.whitecap_wizard_fee}.'
        },
        {
            title: "The Rancor of the Drowned",
            intro: "Sailor’s seldom sleep for long in the Brine Queen’s Boudoir*...",
            details: 'Boarding the side of the ship with kelp covered grapnels are ${Ocean.sub_tables.rancor_boarding}. They are armed with ${Ocean.sub_tables.rancor_armed}. They keep clambering over the rails until ${Ocean.sub_tables.rancor_until}.'
        },
        {
            title: "Waterspouts",
            intro: "Colossal columns of spray snarl in the seas ahead, like hag’s fingers they hungrily grab at the clouds...",
            details: 'The weather conditions ${Ocean.sub_tables.waterspouts_conditions}. The ship, seemingly stranded precariously within, ${Ocean.sub_tables.waterspouts_ship}. Any Old Salt will tell you waterspouts are caused by ${Ocean.sub_tables.waterspouts_caused_by}.'
        },
        {
            title: "The Doldrums",
            intro: "The water is glass and still. Not even the slightest breeze blows and splenetic sails sag slack...",
            details: 'The becalmed waters could last, at least ${Ocean.sub_tables.doldrums_duration}. The most reliable means of survival and/or escape is ${Ocean.sub_tables.doldrums_escape}. Many a sailing ship has met her end in places like this, ${Ocean.sub_tables.doldrums_other_ships}.'
        },
        {
            title: "The Chase",
            intro: "The other ship was spotted only three bells ago, it seems to be gaining ominously...",
            details: 'In the distance, you can just make out ${Ocean.sub_tables.the_chase_distance}. The ship’s speed ${Ocean.sub_tables.the_chase_speed}. The crew ${Ocean.sub_tables.the_chase_crew}.'
        },
        {
            title: "The Message",
            intro: "After some time at sea, it’s easy to grow sick of glancing at the sea near the ship. Good thing you did...",
            details: 'The spotter is the character belonging to ${Ocean.sub_tables.the_message_spotter}. The Bottle ${Ocean.sub_tables.the_message_bottle}. The Message is ${Ocean.sub_tables.the_message_message}.'
        },
        {
            title: "The Tattooed Maiden",
            intro: "She’s always been aboard...you distinctly recall taking her on last port...heavy luggage...keeps to her quarters at least...",
            details: 'In addition to her puissant powers of Suggestion, ${Ocean.sub_tables.tattooed_maiden_powers}. Once aboard a ship, the only way to get rid of a Krakenbride is to ${Ocean.sub_tables.tattooed_maiden_get_rid_of}. Having one aboard isn’t all bad though, ${Ocean.sub_tables.tattooed_maiden_having_one}.'
        },
        {
            title: "Sea Serpents Spawn Here",
            intro: "“The littluns is not too much trouble a-tall. It’s the mothers and fathers (who bear ‘em I swears) that are the worst....”",
            details: 'The first sign is generally ${Ocean.sub_tables.sea_serpents_sign}. The predominant breed here seems to be ${Ocean.sub_tables.sea_serpents_breed}. They seem to prefer this area to spawn because ${Ocean.sub_tables.sea_serpents_reason}.'
        },
        {
            title: "Rogue Wave",
            intro: "A behemothic wave blots the sun. The sailors mutter prayers and oaths. One claps your back and says “See you in the deep.”",
            details: 'Cresting at over 100 feet, the mountain of water ${Ocean.sub_tables.rogue_wave_cresting}. Riding out the wave ${Ocean.sub_tables.rogue_wave_riding}. This harrowing experience is likely to leave the ${Ocean.sub_tables.rogue_wave_leave}.'
        },
        {
            title: "Sargasso",
            intro: "The sounding line started to dredge up seaweed days ago, but now before you stretches a doleful sight...",
            details: 'You can clearly see several derelict ships, but skirting the edges ${Ocean.sub_tables.sargasso_skirting}. Should your ship approach too close, ${Ocean.sub_tables.sargasso_approach}. Marvelous treasures may await within, such as ${Ocean.sub_tables.sargasso_treasures}.'
        },
        {
            title: "The Ghost Ship",
            intro: "Apparently bereft of her crew, ahead a ship pitches on the waves, the tattered remains of sails fluttering...",
            details: 'The Legends in these parts say ${Ocean.sub_tables.ghost_ship_legends}. The vessel is ${Ocean.sub_tables.ghost_ship_vessel}. Sometimes found clinging to the hull of Ghost Ships like remora ${Ocean.sub_tables.ghost_ship_remora}.'
        },
        {
            title: "Should Sea-Madness Strike",
            intro: "A sailor froths and foams at the mouth, shouting incoherently with wild eyes...",
            details: 'The first noticeable symptoms are ${Ocean.sub_tables.sea_madness_symptoms}. A common, Old Seawife’s cure is ${Ocean.sub_tables.sea_madness_cure}. It has long been suspected to be caused by ${Ocean.sub_tables.sea_madness_caused_by}.'
        },
        {
            title: "The Brine Queen",
            intro: "Prayers to Her are on the lips of every sailor who has ever seen rough seas, yet few desire to meet Her...",
            details: 'An undisputed Goddess of All Seas Large and Small, the Queen is also venerated as ${Ocean.sub_tables.brine_queen_venerated_as}. Her avatar at sea sometimes appears as ${Ocean.sub_tables.brine_queen_avatar} in order to ${Ocean.sub_tables.brine_queen_avatar_purpose}. Complete Her task to forestall an aquatic end and receive ${Ocean.sub_tables.brine_queen_task}.'
        },
        {
            title: "The Sirens",
            intro: "Shards of Divine Spark maligned by sages, poets, and sailors alike. The only ones to intervene on a mortal’s behalf...",
            details: 'It is very secret knowledge that their Mother is the Brine Queen and their ${Ocean.sub_tables.sirens_mother}. They always sing in unison, but are seldom found together, their voices ${Ocean.sub_tables.sirens_voices}. Fables lie, poets and balladeers are often mistaken, for their Song tempts by ${Ocean.sub_tables.sirens_song}.'
        }
    ],
    
    // Sub-tables are used by the thematic modules to generate specific details.
    sub_tables: {
        lighthouse_lies_spotter: ["a Jimmy Green barrelman, first time up in the crow’s nest", "a slurring sailor, obviously intoxicated", "the player with the messiest character sheet’s character", "all crew on deck, but with loud disagreements concerning it’s distance and direction"],
        lighthouse_lies_actual: ["a funeral pyre burning on a distant mountain top", "some sort of nautical, mostly-malevolent Will o’ Wisp", "the signal fire, made by the Captain and Crew of a wealthy Merchant wreck, who will reward rescuers handsomely", "the Tower of a paranoid Wizard with a magically lit laboratory on the top floor being the source of the light. A rival to a Wizard Of Waves", "an intentional decoy, set up by a local Wrecking Guild. Ships that heed the light’s warning are destined for the rocks to be ransacked and ransomed", "a gargantuan Anglerfish, up from the murky depths to seek prey, her lure glowing balefully"],
        lighthouse_lies_omen: ["of weal...to anyone who drinks before the sun is over the foreyard", "of weal...by homesick sailors", "of weal...to anyone in the sickbay", "of woe...to the mainbrace, which will surely need splicing soon", "of woe...to devil-dodgers and Clerics", "of woe...whomever last spoke to the Captain", "quite seriously, when in fact it’s likely just corposant on the mast of a distant ship. They’ll try to convince lubbers to perform all manner of hilarious deeds to forestall the inevitable bad luck the sighting must bring", "that the Brine Queen is displeased. You’ll notice the sailors working extra hard and grousing less until the light is far out of sight"],
        lifeboat_adrift: ["for less than a day, one sailor...obviously the Captain will insist that your ship", "for quite some time judging from their emaciated state and the length of their whiskers. From the state of the boat, it looks like they’ve been living on seabirds and turtles", "for seven days and seven nights, with a suspicious outlay of supplies. You spy twelve unopened cases of soft tack and several casks of rum", "”since the Sun was he Sea and the Moon was their home port” is what they’ll tell you. Could it be delirium from being adrift for too long and slaking their thirst with only sea-water, or could there be some truth to it, given their unusual clothes and strange manner of speech?"],
        lifeboat_ship: ["is still miraculously afloat, listing heavily to port, 1d6 Hexes away", "sank swiftly when the hull was perforated by Torpedo Sharks, with their tell-", "was careened on a reef for emergency repairs, when the crew was waylaid by", "became mired in the Sargasso alongside all the others, the rescued speak of the vast treasures that lie waiting among the wrecks, and produce a pouch full of pink pearls as proof", "captured by Gnoll Privateers flying a crossed Flindbar Flag, still plies nearby lanes with it’s Ghoul Crew", "is still tethered to their lifeboat by a forty-four-fathom rope. Named The Snap Tide and these sailor’s refuse to set foot on her decks again, but won’t say why (likely due to ensorcellement). Boarding could be complicated by the new Gull Harpy crew, who are using the sailors as a larder/bait"],
        lifeboat_carry: ["a piece of flotsam, with a nail and string map that appears to lead to land", "ill-gotten gains, in the form of coins that jangle within their boots", "the gnawing guilt of a violating cannibal taboos", "were-rat lycanthropy. They were the first to flee a sinking ship", "mutinous tendencies that could rapidly infect any new crew they come in contact with", "a water-proof strongbox containing three scrolls of Create Tack and Grog", "an invisible Famine Mephit", "a gloved comrade who doesn’t speak. His hands set fire to anything he touches with bare skin"],
        sea_of_storms_prediction: ["Nephelomancy: “Mare's tails and mackerel scales make tall ships take in their sails”", "get a Tarpot good and stitched, spin ‘em around on deck. The direction he falls is where the storm will blow in from. If he falls over the bulwarks, it’ll be a doozy for sure", "specially trained, Homing Crows, each with meteorological messages attached to their legs. They can’t fly far from ship-to-ship, so are only released in the most dire circumstances, and it’s a grave sea-sin to harm one", "ask the Ship’s Skeleton if she can feel one coming in her bones"],
        sea_of_storms_duration: ["at least ...bells (1/2 hour)", "at least ...hours", "no more than …dog watches (two hours)", "no more than ...watches (four hours)", "much longer than ...days", "much longer than ...weeks"],
        sea_of_storms_perils: ["result in torrential curtains of rain, swamping smaller boats", "violently toss about any unsecured precious passengers and cargo", "be preceded by dense fog and low clouds, making navigation difficult or impossible", "flood the galley, potentially ruining the food stores or even drowning the ship’s cook", "require every passenger to do a turn on the bilge pumps, lest the ship take on too much water and list", "start a fire in the forecastle, as a carelessly lit lamp or candle falls victim to a violent downward heave", "sweep a sailor down to the Brine Queen’s Boudoir", "leave a ship foundering without a mast, after a deafening thunderbolt"],
        pirates_crew: ["in this crew are completely green and inept, easily frightened by force", "are successful Hobgoblin Privateers, carrying letters of marque from several nearby nations for plausible deniability", "have the spiky tell-tale frills of Marine Iguana folk, their ’neath the waterline boarding", "fly a flag of Maritime Truce that can hardly be trusted...or can it?"],
        pirates_moment: ["the pirates have yet to sight your ship for some reason", "they have just finished ransoming a valuable captive, and are making for open waters to put distance between themselves and their victims", "their vessel has set full sail toward your ship to give Chase", "they are fleeing a disastrous boarding attempt with a skeleton crew", "the threat may not be from them, but from the small fleet following them", "it would seem they have mistaken the cut of your jib for an allied vessel"],
        pirates_captain: ["is a jovial giant, and very susceptible to flattery and bribery", "has her eyes on bigger prizes, so you may be able to negotiate a toll", "is intensely disliked by the crew, they may use this as an opportunity for mutiny", "’s chest is tattooed with a map of a nearby atoll. “X marks the Spot”", "is the dreaded Kelp-haired Dryad, who hails from Sargasso", "fancies himself a Gentleman/Highwayman of the Seas, polite and courteous", "uses these spoils to fund a guerilla war against a despotic tyrant, always hiring", "is actually a sentient and psychic dolphin-sized ship-worm on the keel, dominating the crew in order to seek out other ships to spawn"],
        krakenspawn_number: ["is thankfully only two, who seem more preoccupied with each other than the vessel", "three to five, with one seeming to orchestrate the actions of the others via a strange, squirmy semaphore and pulsating phosphorescence", "the sea seems to boil with them, as three smaller, strangely humanoid ogre-sized figures clamber and wrench themselves up abeam to starboard, their multiple cutlasses flashing", "has to be more than just one, or else the beast is impossibly large"],
        krakenspawn_beaks: ["can snip a man’s arm clean off in a single snap", "hold on like bear-traps, and won’t release until the beast is good and dead", "are as harder than steel, and can be fashioned into stylish helms", "instinctively target the masts of ships, so focus on those first"],
        krakenspawn_tentacles: ["are extremely tasty, when lightly fried in a hard-tack batter with garlic", "have huge, serrated suckers that leave behind scars that glow faintly"],
        krakenspawn_tenacity: ["know when to retreat, and harbor immortal grudges that they telegraph to all their kind", "often appear shortly before torrential, gale driven rains", "can telepathically communicate with each other, effectively coordinating attacks", "possess eerie powers of vocal mimicry: they will admonish you in your own voice", "can spray sooty and thick magical fog, hampering visibility and staining everything deep indigo", "’s regeneration seems to make two arms appear for each one severed", "seem capable of casting a single magical spell of the third order of power", "are only attracted to ships to test their suitability for transporting a Bride"],
        drying_duration: ["for a few hours, until then the vast pearl beds in reach beckon softly", "until moon rise, perhaps it’s linked somehow to the tides? About a mile or so off, you spy a large wrecked galleon", "for a few days. In the meantime, your oddly exposed and under-defended position is almost more isolating and claustrophobic without the gently rocking waves. Better to not stray to far from the ship, but tempting riches in exposed sunken wrecks and frantically flopping fish stocks may be sought on the sea bed", "until the Brine Queen is appeased via sacrifice and water begins to slowly rush over the damp desert, once more hiding it’s secrets from the sun"],
        drying_theory: ["the sun on these days is just exceptionally hot, and burns away the sea", "Sea Druid pirates have been known to part the Oceans herself in search of prey", "the gradual surfacing of the shell of a massive, miles wide sea turtle as she comes up for air once every few weeks", "a great naval engagement once took place here, and the backs of ghostly mariners steeve the water away once a century as they look for comrades lost", "briny reinforcements being press-ganged for a massive war on the Elemental Plane of Water", "the World Whale eats, but once a man’s lifetime. Drawing in most of the ocean and filtering it through his baleen. Anything smaller than a sloop is destined for his gullet (where supposedly, a thriving Green City dwells, where sailors are treated as Kings and Captains forced to work the kelp fields, while the persistent fiddle music that lulls the beast back into fitful slumber permeates the air)"],
        drying_predicament: ["by the Captain, who begins hurling commands to scour the hull smooth of barnacles and biofouling during this unexpected careening", "by the nearby tribe of Spiny Lobsterfolk and their primitive coral weapons", "as merfolk monks meekly approach to swiftly trade, leaving the ornate shell shrines in which they normally shechanize", "when the Reef Trolls spearing dolphins nearby catch your scent", "by the alien and quixotic, but mostly curious and friendly Urchinfolk", "for a bloodthirsty pod of barbaric Orca Men quickly sniff out your plight", "by the delirious and frightened Liopleurodon, lurching forward with his fins toward your ship", "for your ship has come to rest over the burrow of a colossal and colorful Mantis Shrimp Juggernaut"],
        whitecap_wizard_wizards: ["draw their powers from choppy seas, sighting one is often a sign that seas soon will calm, but hopefully not too much", ", it is said, always keep treasure-filled Coral Towers nearby (for their vessels could not possibly survive at open sea for long)", "are a welcome sight, providing much needed news and entertainment, as well as the odd conjuring of winds for becalmed boats", "hide gills beneath their beards, and receive their considerable magical might from adhering to a strict taboo: their feet must never touch the earth"],
        whitecap_wizard_companion: ["conveniently seeks passage to your destination and can pay handsomely. Surely not a Krakenbride", "is his daughter, Selkie-born and resentful at the prospect of being married off to the first sailor with a decent dowry", "an accomplished Shanty-Slinger, is in search of new adventures and seeks new heroes to humorously weave into her lyrical legends", ", a melancholy Earth Elementalist, is seasick and starting to think that this collaboration was a bad idea", "is actually the true wizard, she conducts most of her business through a more traditional looking simulacrum sculpted from sea foam", ", the Sea Marid: Falonya , two-wishes in. She has recently begun chafing at her Geas to this doddering old fool"],
        whitecap_wizard_fee: ["grain based gruel to direct you to the nearest landmass", "seven silver pieces to speak fish-filling Spells into your nets", "two gills of grog to predict the next weeks’ weather", "three loaves of bread to advise you on a pirate-free route", "any mud from all boots aboard to mark the door of the next sailor to die", "briefly warming by a fire to coerce sweet Southerly Winds to sails", "your Ship’s anchor to cast any spell, nautical in nature", "the youngest soul on board to sell you an albatross charm of Proof Against Demon Waves"],
        rancor_boarding: ["at least a score of barnacle encrusted Skeletal Sailors", "water logged and salt-caked Zombies, dressed in ancient finery purloined from deep wrecks, festooned with fish-hook mail.", "Cast Away Ghouls, maniacally smiling and mostly feral. Their feasting on the flesh of their fellows after shipwrecks cursed them with this state", "the Keelhauled, vengeful and wicked Wave Wights who were betrayed by their crewmates and punished too harshly by their uncaring Captains"],
        rancor_armed: ["corroded dirks clenched in their jaws and the odd stevedore’s hook", "leiomano, shark teeth studded clubs and similarly arrayed mouths for wounds that rip, tear and bleed profusely", "harpoons that limit prey’s movement and waterlogged belaying pins that stun, so the victim can be dragged, still living down to the depths", "sharp swords of serrated sea-glass, jagged and barbed but of masterful make. Usually only found in the hands of Aquatic Elfs", "cutlasses and spongy wooden bucklers. At least two wield Cat o’ Nine Tails that compel the struck to scream out a hidden secret", "untarnished tridents, sacred ceremonial arms stolen from Flying Fish Merfolk. Made of a metal that never rusts, but tends to degrade when exposed to the open air for longer than a day. If immersed in salt-water for a full week, they allow the wearer to cast Swift Swimming once per day"],
        rancor_until: ["the sun rises, or peeks out from behind an inconveniently stubborn cloud", "every bell aboard is set a-ringing", "one of their number is sewn into a hammock and given a blessed burial", "they are Turned twice by a devil-dodger or Cleric", "the anchor is cut and added to the Brine Queen’s collection", "one silver for each sailor aboard is cast into the sea form the forecastle", "until ordered to stop by, or routed when their Spectral Captain standing defiantly upon the waves to port is silenced", "they reach the bow of the boat, where one produces woodworking tools and begins to fashion the figurehead into the likeness of their Queen"],
        waterspouts_conditions: ["include stinging rain and sea spray, rolling off the decks in determined waves. Visibility is rapidly decreasing", "are dominated by the howling, homicidal wind. Sails found unfurled will quickly be shredded to ribbons, and some gusts could buffet a sailor into the drink", "were starting to be almost uncomfortably warm just moments ago, before a dramatic drop in temperature. The crew are hastily donning their paletots", "are eerily calm and almost pleasant, despite the display. They seem to be mostly stationary in nature, but navigating through them still gives you pause"],
        waterspouts_ship: ["flies a distress flag. The wealthy freighter: Risky Endeavors is living up to it’s name. The exotic cloth and spices it carries are worth considerably more than the ship", "may soon be swamped and sink, it carries colonists from a distant land and exotic livestock", "has already been abandoned. See The Lifeboat", "may just be a Morkoth’s illusory bait. Only one of the waterspouts is 'real,' and the others do seem to be mimicking it’s movements a little too precisely", "is a Pirate vessel, and they will be forever indebted if rescued", "was grown and shaped over centuries from a single, massive Redwood Treant (now undead). It seems to sail straight toward the spouts, with strange, hungry nets outstretched"],
        waterspouts_caused_by: ["warm seas and cold winds, nothing more than that", "land lubbers not doing their share of swabbing", "the ship’s cook failing to whistle when stoning raisins and prunes", "Whitecap Wizards, to a one. This is what happens when you refuse to grant them hospitality aboard your boat", "Sea Hag Devilry. Every time. Tossing all socks overboard is the only way to save the ship", "the rarely witnessed wedding ceremonies of Undine royalty", "a tragedy befalling the wives and husbands safe ashore at home, can’t you hear their keening?", "a battle, betwixt Elemental Elders of the Sea and Clouds"],
        doldrums_duration: ["several days, until a fierce Squall awakens the winds", "two weeks, at least the waters are teeming with turtles and sharks", "until the end of the next month, there may not be enough water stocks to keep you alive to see it", "a lifetime. Until a sailor dies to appease the Sky, and personally entreats a Cardinal of Directions in the afterlife, no wind will blow"],
        doldrums_escape: ["prayers...to your pantheons, hopefully one will hear you", "prayers...that a Whitecap Wizard will somehow turn up", "prayers...and pleas to the Brine Queen for mercy, lest she make a widow out of every married man aboard", "desperate...rationing, which should have begun yesterday", "desperate...measures, which could soon include abandoning ship with a oared launch", "desperate...-ly tossing overboard anything heavy, Horses first"],
        doldrums_other_ships: ["but fortunately, you can see an oared Trireme approaching on the horizon", "through weak leadership, a draconian Captain is a key asset", "at the hands of desperate Sea Mad sailors", "by Hammerhead Sahuagin Raiders with their tetoanea and barbed clubs", "but finds new life as a Ghost", "as an overconfident and penurious band of Merfolk Traders will attest as they sell you fresh water for a kings’ ransom", "via ennui, even the strongest stocks can’t feed the gnawing boredom of months with nothing changing", ", a special kind of Sailor’s Hell demi-plane. Did your ship somehow slip through the thin places between Planes as someone slept during the dog watches?"],
        the_chase_distance: ["the copper cladding below the waterline on a galleon at full sail", "a speedy bedar, sailing wing to wing with patchwork sails", "a four-masted windjammer, crawling with crewmen", "a hermaphrodite brig, hull the color of blue flame, with ebon sails"],
        the_chase_speed: ["seems somewhat slowed due to their tacking, but should the winds change", "might not be hard to outmatch, provided the winds cooperate", "is hard to estimate, one moment they appear to be gaining, the next they’re flagging behind", "clearly outclasses your vessel, but some enterprising maneuvers could change that", "could be the least of your worries, as the sea ahead seems studded with dark reefs", "is staggering, they’ll be broadside upon you in no time at all unless evasive action is taken"],
        the_chase_crew: ["are Pirates ..., political prisoners who have taken over a convict ship and still hold the crew hostage", "are Pirates ...that could be mistaken for religious fanatics, they all fight blindfolded and scream prayers", "are Pirates ...of the Cracked Mirror. Vampires, the lot of them", "are Pirates ...trying to warn the players of dangers ahead", "are Pirates ...after one of their own, a deserter who is now a member of your crew", "are the navy of a local nation, your ship just happens to resemble one booked by the kidnapper of their arch-priest", "are Sea Giants, their ship is commensurately large and formidable", "consists solely of the hapless Wonderworker Waspen who somehow managed to not only turn the crew into purple flying fish, but also Awaken the Ship. It has a mind of it’s own and is driven by a misplaced urge to mate"],
        the_message_spotter: ["the player whose first name is last alphabetically", "the player with the closest birthday", "the player who showed up last to the session", "the player who always seems to roll the lowest"],
        the_message_bottle: ["was at one point intended for fine perfume, the copper stopper is somewhat corroded", "is squat and squarish green glass, impressed with text extolling the virtues of a toxic patent medicine", "once housed a valuable vintage of Elf-wine (worth good coin to the right grape-forger), on the label is a magical Scroll of Cleanse Palette.", "a cloudy brown vial, still containing a sip of magical liquid left (Potion of Longevity, 1d6 years)", "a brain-bending Klein Bottle, somehow stoppered with a tiny Cork Golem named Klinkle who likes his belly rubbed", "a medium sized jug, containing a ship. Detects as highly Magical. If you look closely, inside the ship a tiny crew is retrieving a message in a bottle that contains a ship. The message is on the Captain’s desk, four ships in"],
        the_message_message: ["a love letter from one of the PC’s parents to the other", "”Ship dashed upon the rocks, island five days east of Rankport. Plenty more where this came from. LHM” bottle is ballasted with fine pearls", "is a letter of marque, proving that a nearby nation is engaging in piracy", "”Our agreement is nullified, you’ll find three casks of Fire Giant War-Wine buried at the location indicated on the reverse” and a map", "belched out in Magic Mouth: “Next time you find yourself in the Swells, ask for Talbertut. Return this bottle for one free wonder.“", "a Holy writ, already sealed but with convenient blank spaces for the beneficiary. Functions as a Scroll of Raise Dead", "genealogical diagrams proving a local Pretender’s royal heritage", "one very seasick and grateful Djinni named Fleam"],
        tattooed_maiden_powers: ["she is also able to contort her body to squeeze through any opening, port-hole or larger", "as a kind of nautical Fae, her presence on board if ignored, can foul water stocks and even spring leaks in grog barrels", "she serves as a beacon to the True Kraken", "her tresses are tentacles, and she can turn men to porous statues of dead coral with a gaze"],
        tattooed_maiden_get_rid_of: ["beach the ship for three days and three nights, and surround it with salt", "is to hope she takes a fancy to someone on board. She’ll be a challenging wife, but will at least leave the ship alone", "hang a cold iron horseshoe above every entryway", "somehow convince her that the ship already has a Krakenbride", "surrender the bridge, and make her the new Captain. If the crew treats her like a queen until the next Full Moon, she’ll Bless the boat and all it’s sailors. Just hope the True Queen doesn’t grow jealous", "is to simply escort her where she wants to go. It’s usually perilous, and never a short journey. Sometimes it’s not even on this Plane"],
        tattooed_maiden_having_one: ["for it has been said that her sweet singing can rouse the winds, even in the Doldrums", "her tattoos illustrate events that have yet come to pass, but most certainly will. Dependable foreknowledge at sea is rare", "for in a way, she’s an amazing deckhand...all the sailors work harder at her subliminal urging and keep the ship extra tidy and burnished", "they’ve been known to soften (or eat) even the strictest Captains over time", "as no ship with a Krakenbride has ever been sunk", "for once she chooses a ship to nest in, she fiercely defends it with daunting magics, and she doesn’t eat much (or many) for the privilege", "seeing how good she is for the crew’s morale, all aboard will dream the sweetest dreams each night, and even the biggest grouser stops grumbling", "as she constantly exudes a powerful water-soluble pheromone that keeps Sea Serpents at bay"],
        sea_serpents_sign: ["when really small ones (garter snake sized) turn up in nets or on hooks and nip at sailors", "mass migrations of fish, turtles, even sharks give the area a wide berth", "the python-sized one coiled around the sounding line that takes a careless sailor’s hand", "when a large one breaches, almost mast high in a spray of roars and water"],
        sea_serpents_breed: ["mostly benign and herbivorous, munching morosely on kelp, they stare at you cautiously like cows. Taste delicious too", "conventionally Plesiosaurid, but extremely territorial. Biggest one ever caught or killed was the size of a Junk. Their teeth trade well with Merfolk", "eel-like and electrified, they fill the water with a powerful current to stun their prey. Pharyngeal jaws and eerie goat eyes.", "long necked and snub nosed with dozens of frenetic, flapping fins all along their body and twitching barbel-beards. They tend to hunt at night, and if disturbed during the day, cast Darkness", "wood hungry, with saw-like teeth they grind at hulls like rasps. Their bodies are covered in a pale blue magic algae, that when used as a poultice, Heals Wounds and Scars", "related to dragons. They snake through the air without wings, and speak in booming, haughty voices, demanding tribute be dumped into the drink, lest they send you sinking down to visit The Queen"],
        sea_serpents_reason: ["of it’s proximity to ample food sources and usually calm weather", "their ancient genetic homing instinct guides them here to rich and ruddy plankton blooms", "undersea volcanos manage to keep the water surprisingly warm", "the frigid waters here help winnow their large clutches of young", "powerful, undersea Ley Lines converge here", "they are cultivated here. Beneath the waves lies a great Deep Elf city", "this was once a continent dominated by Ophidians. An open dimensional portal to the Plane of Serpents still oozes green light below", "a dead Sea Titan’s corpse has provided food and shelter here for their young stretching back millennia. An impossibly large sword hilt raises well above the waves and is covered in guano and squawking sea birds"],
        rogue_wave_cresting: ["charges forward, you may have just enough time align the bow of your ship appropriately", "seems out of place on an otherwise clear and warm day. It is preceded by a trough so shallow, the hull scrapes the sea bed", "is followed by two sisters, each more damaging than the last", "never seems to break. It is in fact, the mobile bulwark of a rapacious Hydrothermal Vent Giant Sorcerer-King, fashioned from a Charmed legion of Saltwater Weirds"],
        rogue_wave_riding: ["will take an heroic feat of seamanship by every member of the crew", "may not be possible without the aid of magic, fortunately you can just barely make out the decorated sails of a Whitecap Wizard’s small sloop", "will deposit your ship 4d4 Hexes away in a random direction, potentially beaching your boat, or causing it to come to a crashing rest deep inland", "washes your ship dangerously close to a large reef, replete with a small calcified keep. It serves as an abbey to several friendly Brain Coral Golem squid ink Scroll Scribes with an off-putting appearance", "seems hopelessly impossible until, until an enormous Bronze Dragon swoops down and snatches your ship from the sea’s surface like a plucked petal. Draco Ex Machina. Her name is Brightsand, and the debt of thanks she expects to be repaid with may often have you returning to this moment", "is likely to both impress and anger the Brine Queen"],
        rogue_wave_leave: ["...visibly shaken and exhausted, with only minor injuries", "the crew...reduced by 1d12 sailors", "the crew...on the verge of mutiny, insisting the ship turns back", "the ship...weathered the wave surprisingly well, minor damage", "the ship...lost a mast and or/sails, speed dramatically reduced", "the ship...’s lower decks are full of water, and the ship begins to list", "the ...food and water stocks virtually depleted, you have enough for 1d4 days of sail before the situation grows more desperate", "the ...Captain of the ship Sea Mad"],
        sargasso_skirting: ["may prove tricky, as the powerful gyre seems to draw your ship nearer and nearer toward the mass of vegetation", "you spy a recently ensnared arrival: A sturdily built War Junk from the Terracotta Republic, a distant nation of sentient Living Statues", "is the Shoal Halfling scavenger caravel The Disappointment, who may see your ship as easier pickings", ", a shiver of Longfin Makofolk battles a fever of Stingray Men for territory, the losing side calls to your ship for aid, promising plunder gleaned from abandoned galleons"],
        sargasso_approach: ["strangling, leafy runners will rapidly begin climbing the hull. Taking only moments to reach the decks. Like kudzu, if left alone, soon all you will see is a slick leafy-green vaguely ship-like shape", "or the navigator becomes distracted by the air thick with curious Seaweed Sprites, it too will become part of this maritime mausoleum", "you may draw the attention of the primary resident: a Maricolous Druid, obsessively collecting sea-going vessels as part of some long-forgotten Geas", "it is liable to be harried by the true nature of the Sargasso: An fanatically territorial thicket of Aquatic Shambling Mounds", "one is likely to be approached by cautious Hippocampi-Centaurs", ", sea-lonely sailors are likely to desert without a second thought when beckoned by the numerous Kelp Dryads who make their home here"],
        sargasso_treasures: ["a floating garrison, mired here on it’s way to reinforce a forgotten war. Full of weaponry, some of which may prove magical", "an Immovable Anchor, Dwarf-make, command word translates to a curse", "a very special Sleuthing Spyglass, a stubby switch on the side can be depressed to show past events at sea", "the Pirate Ship: Patience, it’s hold laden with plunder from the collapse of the Gargoyle Empire", "a barnacle encrusted Kwalishi Apparatus, containing a small Spell library", "the sacred bones of Saint Luchet the Scapegoat, each piece of his skeleton is a valuable and highly portable holy relic", "the golden Godship of Olifrax the Ungenerous. The entire hull glimmers in the sun. It’s only gold leaf, but enough could be scraped off in a weeks’ work to lease a small armada", "a king’s ransom, along with the true king in arcane stasis below deck. How will the kingdom react when they discover they’ve been ruled by a double-walker for the past two decades?"],
        ghost_ship_legends: ["sometimes, for reasons unknown the Sargasso frees a ship from it’s verdant clutches to spread seed throughout the seas", "once a year, on a the last New Moon, their Captain’s are given a chance to atone to the gods for their sins against sailors. Almost all of their egos are too proud to humble themselves in this fashion, but heroes have been known to convince them otherwise", "that some ships are doomed to sail forever after falling pray to the pirates of The Cracked Mirror", "anyone who hoists their flag upon the mast of a Ghost Ship is granted an obscene mastery over Death herself, in the form of Undead Control"],
        ghost_ship_vessel: ["abandoned, but easily boarded by the brave. Perhaps an investigation can uncover what led to it’s current state?", "a highly mobile schooner stronghold for The Drowned", "is an infamous Ghost Ship: The Celestial Marriage, often seen as a portent of ill omen", "a Draugr Dragonboat hailing from the bleak, skeleton-strewn shores of the Northern Necrocracy", "actually an Astral Ship, blown far off planar course, crewed by intelligent plane-hopping arachnids in distress", "a Balefire Bireme, aglow with ghostly flame. It will initiate ramming maneuvers, even though it’s completely incorporeal. The flames only burn combustible items like metal and stone"],
        ghost_ship_remora: ["are patches of phosphorescent algae, enhancing it’s eerie appearance", "are Figure Head Golems, craving to be liberated to the bow of another ship", "one could discover Magebane Anemones. Curious creatures that filter feed on latent arcane energy", "are Jenny Haniverfolk Penitents, engrossed in meditative pilgrimage", "is a species of barnacle, it’s shell a Death’s Head, that is said to allow the consumer to Speak With The Dead", "Spectral Suckerfish, feasting on the negative energy left in it’s wake", "one may find the wickedly barbed Mermaid Purses containing underdeveloped, but still malevolent Ixitxachitl", "are 2d6 Spellworms, actually a mollusk, that when dried carefully over the course of a few days, become single use Magical Wands"],
        sea_madness_symptoms: ["virtually indistinguishable from melancholy", "an incredible thirst for sea water and an intolerance of alcohol", "small, starfish-shaped, and itchy skin lesions, followed by eyebrow loss", "redness between the fingers and toes as webbing begins to slowly form, followed by a sore neck and shortness of breath"],
        sea_madness_cure: ["four spoonfuls of anchor shavings and a haircut, but only after the boat was moored during a Full Moon", "throwing all cups and cutlery on board over the side, into the sea", "seal’s liver served in a spicy Salmagundi. The right peppers are said to grow on land that’s only a few days sail away", "blood-letting via thirsty Lampreyfolk Chirurgeons", "marriage to a Merfolk, the sickness will immediately return if the patient ever neglects or speaks ill of their spouse", "stich ‘em up through their nose in their hammock and toss ‘em in the drink before the whole ship goes mad"],
        sea_madness_caused_by: ["a diet rich in seafood, but poor in fruits and vegetables", "ship rats, whispering in a sleeping sailor’s ear", "the steady, interminable, rocking motion of a life at sea", "accidentally catching sight of the Evil Eye pattern on a Doom Turtle’s shell", "the venom of a tiny, snowflake-like jellyfish", "a Krakenbride fouling the grog", "drinking sea water and sleeping on watch", ", what else could it be, but a sign of the Brine Queen’s favor?"],
        brine_queen_venerated_as: ["Nugur: the God of Bounty and Harvest by most in the Underdeep", "Rashitri: the Goddess of Revenge in any city with a significantly large enough port", "Saresidisa: the Muse of Nostalgia and Death, primarily by Poets and Painters", "She Who Taught Us To Tear Mountains: abdicated Empress of the Elemental Plane of Water, an Old One...worshipped by Doomsday Tsunami Cultists the world over"],
        brine_queen_avatar: ["an Old Salt", "your ship’s Captain", "an Albatross Roc", "each and every Dolphin", "a Dire Zaratan", "nine Rogue Waves"],
        brine_queen_avatar_purpose: ["augment Her army of Drowned", "foil her daughters, The Sirens", "keep a balance between the death of ships and whales", "recruit Sailors to Her Clergy", "grant fickle favors to faltering favorites", "advance her agenda to reclaim all land from her sneaky Sister"],
        brine_queen_task: ["dismantle a Dam to receive an easily misconstrued blessing, Breath Water and Swim As A Shark permanently", "drink from seven seas to receive a commission in one of her many legions of Drowned", "discover an island to receive victory at sea, the bigger the naval battle the better", "destroy a Sea Dragon to receive your life in a Conch Shell. Listen at any time to recall anything you have ever heard exactly, or any conversation about you", "defeat a Kraken to receive your choice of vessel, from every boat ever or yet to sail these seas", "discipline Her Daughters to receive a Spell that will split your soul into several thousand fish. You cannot be killed while one remains, even if it only lasts a day at a time", "deliver her regrets to the God of Storms to receive Immortality at her side as a Skeleton, at least until she tires of you", "drown Her Sister to receive your price, named by you"],
        sirens_mother: ["Father is the Sun. They were conceived in a dalliance during very first sunset over the sea", "other parent is the first sailor to ever go to sea, which explains their desire to aid mortals", "birth was parthenogenic, antibodies against the disease of Ships, turned sympathetic", "children are the Sea Serpents, it was the primordial Ophidians who could not resist their rhythmic song, and molded their mammalian slave caste into their scale-less image"],
        sirens_voices: ["flatter the Ugly and Insecure, showering them in gentle flurries of accurate compliments", "encourage the Clumsy, steadying even the most shaky of hands", "succor the Sick, wholly healing both body and mind", "tutor the Dull, imparting hereto absent insight and knowledge", "invigorate the Weak, making them capable of superhuman feats of strength", "suffer the Foolish, broadcasting their bliss for all to finally fathom"],
        sirens_song: ["revealing future and past events, with unerring accuracy. Listeners will know their lives' triumphs and even their dooms as weighed on the Scale of Heaven", "hinting at their knowledge of methods that can hide one from their Mother", "promising to banish all fears, forever and impart everlasting, unshakable hope", "granting faith to the faithless and gnosis to the faithful", "spewing forth revelations of self-realization, and righting even the most crooked path", "tailoring it’s wordless lyrics to every ear: The Wizard will be teased with tidbits of powerful spells, while the Fighter rip-roaring tales of martial prowess, etc", "illuminating all weaknesses, and providing the way to overcome them", "unravelling the very secrets of song itself, a captivating fractal that slowly unfolds the origin and complete comprehension of all languages"]
    },

    // --- EXPANDED ENCOUNTER LIST ---
    encounters: [
        "a pod of dolphins", "a flock of seagulls", "a distant ship on the horizon", "a lonely mermaid on a rock",
        "a Sahuagin raiding party", "a merchant galley", "a Pirate galley", "a pod of Tusked Whales",
        "a Giant Crab scuttling on the sea floor", "a Giant Sea Turtle", "a Dragon Turtle",
        "a group of Merfolk traders", "a whirlpool that appears suddenly", "a ghost ship, crewed by the damned",
        "a massive Sea Serpent", "a school of Sharks", "a gargantuan Squid", "a tribe of Aquatic Elves",
        "a group of Tritons riding hippocampi", "a Bronze Dragon flying overhead"
    ],
    discoveries: [
        "a patch of calm water in an otherwise choppy sea", "a floating barrel of fine wine", "a message in a bottle containing a treasure map",
        "a small, uncharted island", "a shipwreck, old and barnacle-covered", "a ghost ship that vanishes when approached",
        "a floating treasure chest, trapped and locked", "a beautiful coral reef teeming with life", "a strange, magical fog that rolls in suddenly",
        "the colossal skeleton of a sea monster on the ocean floor"
    ]
};