// tables/tables-desert.js

export const tables = {
    // High-level thematic modules for a desert hex.
    thematic_modules: [
        {
            title: "A Pertinacious Pilgrimage",
            intro: "There’s safety in numbers in the desert... Nearly three score penitents stride slowly into the sun...",
            details: 'The procession marches ${Desert.sub_tables.pertinacious_procession}. Their destination ${Desert.sub_tables.pertinacious_destination}. Among the items within their processional ark ${Desert.sub_tables.pertinacious_ark_contents}.'
        },
        {
            title: "The Camel Market",
            intro: "“Best Humpbeasts this side of Brigadoon!” cries an excited hawker as dozens of camels bleat and grunt...",
            details: 'The camel sellers in these parts ${Desert.sub_tables.camel_market_sellers}. When you examine the merchandise, you should do so ${Desert.sub_tables.camel_market_merchandise}. The discerning customer may notice one very unusual camel: a ${Desert.sub_tables.camel_market_unusual_camel}.'
        },
        {
            title: "The Neophytes",
            intro: "Four old men with oddly kind faces busy themselves with grisly work around a partially flensed carcass...",
            details: 'The carcass ${Desert.sub_tables.neophytes_carcass}. The four men ${Desert.sub_tables.neophytes_men}. Easily overlooked, within the creature’s stomach is a bezoar ${Desert.sub_tables.neophytes_bezoar}.'
        },
        {
            title: "The Banished",
            intro: "A group of seven small children huddle near an ancient stone wall, their faces horribly misshapen...",
            details: 'The children here ${Desert.sub_tables.banished_children}. They were cast out into the barren wastes ${Desert.sub_tables.banished_reason}. Unexpected protection for the children comes from ${Desert.sub_tables.banished_protection}.'
        },
        {
            title: "A Dead Lake",
            intro: "What first seems to promise reprieve for parched throats quickly turns to disappointment...",
            details: 'Circumnavigating the lake ${Desert.sub_tables.dead_lake_circumnavigation}. Near the banks, ${Desert.sub_tables.dead_lake_banks}. Beneath the brackish surface, ${Desert.sub_tables.dead_lake_surface}.'
        },
        {
            title: "The Stoic Stones",
            intro: "For as far as the eye can see, giant stones stand like soldiers at attention, arrayed in formation...",
            details: 'The gigaliths are regularly spaced two pike-lengths apart and ${Desert.sub_tables.stoic_stones_gigaliths}. Finding one’s way through ${Desert.sub_tables.stoic_stones_finding_way}. An ambush while traversing the Stones is most likely to be ${Desert.sub_tables.stoic_stones_ambush}.'
        },
        {
            title: "The Basalt Plain",
            intro: "Uncannily uniform hexagonal stones compose the surface of the ground here...",
            details: 'The surface of the land here ${Desert.sub_tables.basalt_plain_surface}. The many furrows and scars here ${Desert.sub_tables.basalt_plain_scars}. This area is sacred to ${Desert.sub_tables.basalt_plain_sacred_to}.'
        },
        {
            title: "An Abandoned Wagon",
            intro: "With no one in sight, a covered wagon with no team to pull it seems to crouch forlornly in the sand...",
            details: 'The wagon ${Desert.sub_tables.abandoned_wagon_condition}. Its former owners ${Desert.sub_tables.abandoned_wagon_owners}. Found within ${Desert.sub_tables.abandoned_wagon_contents}.'
        },
        {
            title: "The Anchorite's Retreat",
            intro: "From a cave carved into an altar-rich alcove into the side of an escarpment, smoke from a campfire curls...",
            details: 'The Hermit has a complicated relationship with The Lich which embodies ${Desert.sub_tables.anchorite_relationship}. The Hermit is able to ${Desert.sub_tables.anchorite_ability}, but only if he can ${Desert.sub_tables.anchorite_condition}.'
        },
        {
            title: "The Lich Seat",
            intro: "Wrapped in a windswept gown of samite, a skeleton seated atop a decapitated obelisk surveys the desert...",
            details: 'This Lich ${Desert.sub_tables.lich_seat_description}. If engaged in combat, ${Desert.sub_tables.lich_seat_combat}. If approached deferentially, ${Desert.sub_tables.lich_seat_approach}.'
        },
        {
            title: "The Hungry Sands",
            intro: "Descending that last dune was arduous, you sigh with relief at the level land ahead...",
            details: 'The quicksand ${Desert.sub_tables.hungry_sands_quicksand}. The easiest way to traverse is by ${Desert.sub_tables.hungry_sands_traverse}. To complicate the crossing, ${Desert.sub_tables.hungry_sands_complication}.'
        },
        {
            title: "The Horned Titan",
            intro: "Jutting up from the flat surface is a massive stone formation, closely resembling a head with horns...",
            details: 'Local legend tells that he was petrified ${Desert.sub_tables.horned_titan_legend}. The scraggly grass here ${Desert.sub_tables.horned_titan_grass}. A tiny village rests atop the forehead, which is ${Desert.sub_tables.horned_titan_village}.'
        },
        {
            title: "An Oasis",
            intro: "Everything is a sight for sore eyes in this blazing sun, but the smell of flowing water quickens your pace...",
            details: 'The current visitors include ${Desert.sub_tables.oasis_visitors}. The water here ${Desert.sub_tables.oasis_water}. Staying longer than a day ${Desert.sub_tables.oasis_staying}.'
        },
        {
            title: "Sky Burial",
            intro: "Raspy hisses and squawks give away a wake of Vultures patiently hopping around a shrouded body...",
            details: 'Investigating the corpse ${Desert.sub_tables.sky_burial_corpse}. Among the grave goods/burial offerings ${Desert.sub_tables.sky_burial_offerings}. These unusual vultures ${Desert.sub_tables.sky_burial_vultures}.'
        },
        {
            title: "Sandships",
            intro: "Like flower petals tossed in the breeze, the equally unexpected sight of sailing ships upon the sand appears...",
            details: 'They are crewed by ${Desert.sub_tables.sandships_crew}. They seem to be fashioned from ${Desert.sub_tables.sandships_fashioned_from}. Booking passage to another Hex ${Desert.sub_tables.sandships_booking_passage}.'
        },
        {
            title: "The Polyandrium",
            intro: "The keening winds of the desert seem to mourn the sight ahead, thousands of crowded graves dot the dunes...",
            details: 'Interred here ${Desert.sub_tables.polyandrium_interred}. The grounds are maintained ${Desert.sub_tables.polyandrium_maintained}. Bestowing a donation at the simple shrine here ${Desert.sub_tables.polyandrium_donation}.'
        },
        {
            title: "Sudden Sandstorm",
            intro: "It came out of nowhere, blotting the sun from the sky as a furious gale screams across the sands...",
            details: 'The sandstorm ${Desert.sub_tables.sudden_sandstorm_storm}. Your nearest chance of sheltering ${Desert.sub_tables.sudden_sandstorm_shelter}. Among the aftermath, ${Desert.sub_tables.sudden_sandstorm_aftermath}.'
        },
        {
            title: "Necropolis",
            intro: "It is said that due to a curse, those who succumb in the desert never find their rest, but still thirst for the blood of the living...",
            details: 'This Necropolis is centered on ${Desert.sub_tables.necropolis_centered_on}. The Undead here consist of ${Desert.sub_tables.necropolis_undead}. This one will continue to spawn Undead until ${Desert.sub_tables.necropolis_until}.'
        },
        {
            title: "The Mirage",
            intro: "Far on the horizon, amidst the shimmering haze of the heat of the day, you can barely make out...",
            details: 'The mirage shows ${Desert.sub_tables.mirage_shows}. Trying to reach it ${Desert.sub_tables.mirage_trying_to_reach}. But one just might, if ${Desert.sub_tables.mirage_if}.'
        },
        {
            title: "She Who Rules Herself",
            intro: "None of the denizens of the desert will speak of her, yet all of them seem to quake in terror at the thought of her...",
            details: 'Although her size shifts at will, She is currently ${Desert.sub_tables.she_who_rules_size}. But her true nature is even more startling, as Her venom ${Desert.sub_tables.she_who_rules_venom}. Countless men have died trying to destroy Her, because she may only be felled by ${Desert.sub_tables.she_who_rules_felled_by}.'
        }
    ],

    // Sub-tables are used by the thematic modules to generate specific details.
    sub_tables: {
        pertinacious_procession: ["with each step punctuated by the crash of several brass cymbals. Through the din, they will tell you the noise is intended to ward off evil spirits", "in methodically synchronized steps, along ancient furrows. It seems similar treks have been taking place for centuries", "with a forlorn, shuffling gait. All heads bowed: every member blindfolded with exotically embroidered crimson and silver cloth", "unsteadily, for they are on their fourth day of fasting, and have abstained from water since sunrise. You spy one member drop to the sands, and the others behind pay it only enough heed to gingerly avoid stepping on the body"],
        pertinacious_destination: ["is about three Hexes away through dangerous heathen territory, anyone bearing weapons will be welcomed to join them and paid for their service", "has several stations, the first of which will only be revealed to the Pilgrims by The Hermit", "is sacred and secret. Persistent inquiry could lead to trouble unless a party member dedicates themselves to a member of their unusual pantheon of elemental spirits", "is The Polyandrium, to entomb a tyrannical, beatified, paladin", "may be nonexistent. From the tracks in the sand, it appears that they continue to march in a large spiral pattern, expanding outward", "could be The Lich, an ancient pact insures that they receive a few minutes of modest rains in exchange for expensive and lavish gifts"],
        pertinacious_ark_contents: ["are offerings of rice, each grain engraved with a name", "is considerable coin, alms for The Banished", "...holy texts, which instantly translate to the reader’s native language", "are several canopic jars containing the preserved organs of an angel", "is a heavily tattooed Halfling Vestal, destined for sacrifice", "is one too many femurs for a complete skeleton. The bone can Locate Water", "is a pair of gold embroidered sandals that can case Cloudstep once daily", "is a potent magical item: A Sandship In A Bottle"],
        camel_market_sellers: ["have a reputation of honesty, almost to a fault. They are quick to point out deficiencies with their merchandise", "are well known for their sincere love of haggling, they will be incredibly offended if you don’t insist on bargains and hurl the customary insults about their merchandise", "should be dealt with cautiously, stories of bargain Camel/Kelpie hybrids abound, and all it takes is an Oasis to reveal their nature", "really do provide the best trained Camels, but the animals should never be mistreated, nor be on the receiving end of the lash. Each merchant here is a devoted Dune Druid"],
        camel_market_merchandise: ["carefully for these beasts often like to playfully bite prospective buyers", "but be weary of competing bidders driving up prices if you show too much interest in a single animal", "swiftly, for an approaching haboob has everyone anxious", "and be prepared to pay only in silver, for the merchants are forbidden by ancient taboo from accepting gold for their wares", "with particular attention to the teeth. It’s said a camel with a missing front tooth is good luck and requires less food", "but don’t look too closely at ornate patterns shaved into their sides. Some are magical sigils akin to Hypnotic Patterns and have a Charm Buyer effect"],
        camel_market_unusual_camel: ["calf, jet black with red eyes. Smells of brimstone and smoke. Do Camels have Nightmares?", "Awakened after overhearing a sermon from the Anchorite", ", seller, who is the spitting image of one of the PCs", "-shaped megalith. The superstitious always walk their new camels counterclockwise around it before embarking on a journey (as Bless)", "skeleton, animated and loyal to Clerics. Looted from a Necropolis", "with a magnificent beard. Actually an ancient Dwarf Cuneiform Scribe named Irem, polymorphed by a tomb curse he mistakenly translated that also granted him immortality. Resigned to his fate, but chatty once purchased", "bit and bridle, magically endowed to keep the rider clean and cool", "a beautifully carved Olive Wood Golem in the form of a camel, needs no water, food, or rest. The hump can be opened for storage and is watertight"],
        neophytes_carcass: ["appears to be some sort of large desert predator, perhaps a Lion or Sand Panther", "has oddly reptilian features and teeth/claws that glow a sickly pink", "twitches slightly as the old men hum a tuneless ditty", "’s bones are rapidly turning into sand, so the men work quickly"],
        neophytes_men: ["appear to be preparing the carcass for some kind of mummification, they smile as you approach and offer the PCs figs and water", "are not willing to allow food to go to waste in the lifeless desert, and are butchering the beast for their nearby shrine to the Rain Goddess", "have all had their tongues removed for whispering heresies, making communication difficult. They are more than willing to write out their religious philosophies in the sand however", "slyly size up the party. Each is an apprentice Necromancer, “recruiting” for a nearby Necropolis", "are newly afflicted Were-Vultures, during the day they are banished from the sky and forced to wander the desert sands as men, but their newly found instinctive attraction to carrion is impossible to deny", ", diurnal Desert Ghouls only recently risen. They know this area (and adjacent Hexes) intimately, they are surprisingly good-natured (having just eaten). They are willing to serve as guides/water porters if fed a camel’s worth of meat for each week’s service."],
        neophytes_bezoar: ["...is worth at least a handful of platinum to the right collector", "is a Periapt of Proof Against Sand Fleas", "is a Periapt of Proof Against Venomous Bites", "is a Periapt of Proof Against Poison", "is a Periapt of Proof Against Ghoul Paralysis", "is set within a Signet Ring that once belonged to a local Prince", "is about the size of a fist a powerful reagent in a ritual that could purify an entire body of water", "is composed of hair, allows anyone who swallows it to Speak With All Haired Animals"],
        banished_children: ["eke out a meager existence, trading alms from the kind-hearted for water and sustenance", "are all siblings, but forgot their names long ago", "have surprisingly articulate speech and are uncharacteristically cheerful: They see their predicament as just and try to make the best of things", "are just the vanguard. The 'village elders' if you will. Nearby is an entire bustling City of Children. Intricately carved from sandstone with an ever-full well and their own laws, government, and industry. A party that gains the trust of each of these respected leaders may be invited to shelter within, but is never permitted to stay more than seven sunsets"],
        banished_reason: ["by cruel local taboos against unseemly things", "due to a magic-resistant form of leprosy", "mostly of their own volition, they didn’t want their curse to spread", "after outliving their usefulness, the Sidewinder Naga only needs so many novel noses and spare body parts for her morbid parties", "due to their undead, zombie nature. All children are firstborn sons and daughters of noble houses, cursed to 'never die' by a back-handed bargain made with a sadistically literal Wonderworker", "because of their horrible appearance and the shame it brings, each was brought before the Disc Of Toeth in hopes of being a suitable supplicant, and each failed the Silent God’s unknown criteria"],
        banished_protection: ["the Spitting Sand Cobras they have tamed and trained for defense", "a pack of Clockwork Brass Jackals that spit molten metal", "a Saguaro Cactus-ent who possesses powerful weather magics", "a powerful and fiercely protective Blue Dragon: Merceleen, suffering from an empty nest after her only egg was stolen", "the Sands themselves, two puissant Genii Loci claim them as part of their bodies, and compete fiercely for their affection", "The Anchorite, who feels responsible for their current state from misguided prognostications he provided as a youth", "a banner of Lawful Moloch-men (thorny devil) Knights, armed with barbed lances, astride their Pachycephalosaurids", "why The Lich, of course...each child here is one of her direct, if distant, descendants"],
        dead_lake_circumnavigation: ["will take the better part of a day to accomplish", "may not be necessary, it only appears to be about knee deep", "on the far shore is a troupe of nearly twenty stubby-legged Gila Monsterfok in antique bronze armor", "are the unpredictable trails of several sigil-carved Sailing Stones on the slowly expanding playa. It is said sleeping in front of one grants a Spell to the sleeper"],
        dead_lake_banks: ["a small herd of Spiral Horned Addax licking a salt encrusted statue", "parades a flamboyance of Flamingos, their pink plumage seems like the only color around for miles", "are several large, intriguing funnel shaped depressions in the thin sand (the hunting pits of Larval Ant-Lions, the size of manticores)", "squats a small, squamous shrine to the Chaos Toad Gods", "shallow rectangular evaporation pools of brine, the salt here is being raked into surprisingly uniform mounts by a team of tan colored Mantis-men", "strange, calcified and salt-encrusted skeletons of creatures, including a wyvern, stand bleakly among the tufa. Why do they all seem to be watching you?"],
        dead_lake_surface: ["the only life to be found are tiny brine shrimp", "is a king’s ransom in salt, if only there were a way to transport it", "swim schools of strange, flat Cactus Fish that are extremely delicious if their toxic spines can be avoided", "are the creches and nurseries of Sand Sharks", "are the barely visible capitals of columns that line an inundated tomb", "are the gilt remains of a Asp-Prowed Gondola, from Ophidian antiquity", "at the center of the lake is an Infernal Duke, bound by the strangely concentric circular salt boundaries by a crafty summoner. Only a few more millennia of rain before he’s free", "one can barely make out an uniform arrangement of what appear to be hundreds of smooth and round stones. On a closer look, the cranial sutures reveal these to be skulls"],
        stoic_stones_gigaliths: ["are weathered limestone, embedded with remarkable fossils of spiral shells, strange fish skeletons, and other prehistoric sea-life", "seem to be composed of an unusual form of granite, not typically found in this area. Some seem to bear foot and handholds", "feature bark-like texture in places where the wind hasn’t sanded and scoured them smooth: Could these be petrified tree trunks? Part of some ancient behemothic orchard?", "groan audibly in a great, rumbling din as they slowly rotate and seem to follow the sun’s procession across the sky. Are those faces, or just the interplay of light and shadow?"],
        stoic_stones_finding_way: ["would be more pleasant, if the journey wasn’t continually punctuated by alternating cooler shade from the stones and scornful, scorching sun", "could be hampered or hindered by the 'helpful' arrows and signs scratched into some stones by previous travelers", "should be simple, if you’re willing to pay the exorbitant water-toll to the long-legged Silver Antfolk Myrmidons for traversing their territory", "might result in meeting up with a hopelessly lost caravan, transporting exotic intoxicants and contraband. They will pay handsomely for assistance", "is difficult and one could easily lose oneself in the maddening titanic repetition and pullulating feelings of sheer personal insignificance", "may not be possible without the aid of magic, a days journey will only result in you exiting from the same place you entered. What’s at the center?"],
        stoic_stones_ambush: ["bandits, led by a Dusk Elf with a Spear of Desiccation", "from above by voracious Desert Geckos, the size of lions, that cling to the shady sides of the stones", "spindly Fulgurite Elementals eager to end the suffering of their dual nature", "by the parties own pack animals/mounts: Any animal walking through the stones is Awakened", "witnessed between three aggressive Sand Wraiths and a shiny tonsure of Scarab-Man Monks carefully rolling their prayer ball", "...Scula, the Gnoll Queen and her fanatically loyal Dervish harem", "Scorpion Man slavers, utilizing pits and non-lethal traps to harry their prey", "Shrieking Wyverns who nest atop certain guano stained stones and viciously defend their territories"],
        basalt_plain_surface: ["periodically rises in massive angular, geometric plateaus that provide some degree of welcome shade", "is infernally hot, scorching even the insulated pads of camel feat", "may not be as solid as it looks, some of the hexagons are merely centimeters thick over a large, depleted aquifer", "demonstrates it’s uniformity due to the fact that these are simply the pores of a massive, and hopefully dormant visitor from the Elemental Demi-Plane of Volcanic Rock"],
        basalt_plain_scars: ["make an excellent place to camp, as the basalt seems to store heat well against the freezing desert nights", "occasionally contain tiny rivulets of pure, fresh water distilled from dew", "are heavily decorated with antediluvian petroglyphs, some housing bizarre Primeval Spells that can be inadvertently cast by finger tracing or rubbings", "each contain a strangely colubrine skeletal remains and shards of strange obsidian pottery, have all these tombs been looted?", "are hungry mouths, like stony Venus Flytraps", "result from a dramatic clash between colossal Dragons. It’s said the bones of both the victor and his victim can be found somewhere within the plain"],
        basalt_plain_sacred_to: ["Haze Mephits, who rely on the shimmering Fata Morganas for breeding", "a troupe of wise and literate Rock Baboons", "a group of doomsday Magma Cultists who fling Greek Fire", "the Hobgoblins Khanate, who abandon their infants here to survive on their own as a crucial rite of passage. Hobgoblin babies don’t cry: they snarl", "a secret cabal of lazy column builders who jealously guard their bounty of shortcuts", "a prominent Hematite Dao Noble, who has grand palatial schematics in hand", "a prominent figure in the faith of a PC, it was here that they met their end", "the minor Godling of Tessellation, capricious but Lawful. Any repeating pattern could be misconstrued as a prayer"],
        abandoned_wagon_condition: ["was abandoned quickly, as the flaps were not tied down and are blowing in the desert winds", "is firmly stuck in the sand, requiring a few hours shoveling, or the camel-power of at least four beasts to extricate", "has a broken axle, which may be way it was discarded in the first place", "’s cloth cover is a hibernating Cloaker Mimic who has recently fed"],
        abandoned_wagon_owners: ["were a group of Pilgrims", "are just down the dune. A party of adventurers, enjoying thick coffee and strategizing about their next move", "found themselves waylaid by Coyote-Men Zingari who still lurk nearby", "’ bodies can be seen nearby, partially buried in the shifting sands, their bodies and faces contorted with what appears to be laughter", "shouldn’t have strayed so close to a Necropolis", "ran out of potable water, but were rescued by friendly Darkling Men"],
        abandoned_wagon_contents: ["are only bloodstains and an adamantine key", "are adequate stocks of preserved food, two goatskins bloated with water and a tin cage containing a songbird", "a map of winding route through The Stoic Stones with several “X”s and the quick scrawl “find them here”", "several large burlap bags of buckwheat groats, within one is a cache of high denomination electrum coins inside a jar containing a dead scorpion", "a heavily sedated and restrained Paladin, named Chanderad. More than willing to join a just cause if released and armed", "a small stone sarcophagus full of a elderly Androsphinx’s bones, missing the skull, among which is a Rod Of Riddles (d12 charges)", "a Blue Dragon egg, recently robbed from Merceleen’s nest", "are a few small animals: familiars that each immediately bond to a single PC’s, providing attribute increases and 1d6 spells/day"],
        anchorite_relationship: ["Temperance: it is only his self-restraint that has prevented him from acting", "Charity: Suffering a Lich to live", "Diligence: his attempts to draw The Lich into the faith have so far been unsuccessful, but it has not stopped him from trying", "Patience: all things end, even Liches", "Chastity: the two were in love platonically once, and perhaps still are", "Humility: are we really so different? Are we not simply two sides of the same coin?", "Kindness: it is only moral to love thy neighbor", "none of the above, the Anchorite is a consummate charlatan and liar. The Lich is honest at least."],
        anchorite_ability: ["direct the party to the shortest route to their destination...", "provide cryptic hints concerning the location of The Lich’s phylactery*...", "cast any divine spell known to mortal man, and some only available to Gods...", "all of the above, for three completed trials below:"],
        anchorite_condition: ["retrieves a flowering herb that only grows within The Hungry Sands", "deliver his latest Revelation to The Pilgrims. No peeking", "anoint The Banished with water from The Dead Lake", "the party is able to destroy 2d6 Necropoli", "each player switches character sheets with another for a session", "She Who Rules Herself is exterminated"],
        lich_seat_description: ["is known as the Arbiter of the Skies, able to control and influence the weather", "achieved semi-divinity years ago through self-actualization and contemplation and can grant prayers and act as a divine patron for her Jackal Men servants", "has direct control over all active Necopoli, and the ability to generate a new one within a random hex once per week", "serves as the desert’s anchor, almost like a pole (all compasses in the desert point to her). Gradually radiating out from her, the sands could eventually swallow the world"],
        lich_seat_combat: ["she will appear to her attackers as their native sovereigns, and using mental magic attempt to force them to bow and genuflect", "her touch removes not only life-levels, but also steals abilities/skills of the victim which she can use without error", "her gown animates offensively, anyone enveloped in it’s folds is Plane Shifted to the Umbral Plane", "the ground will burst forth with d100 Skeletons that precisely resemble her", "the Obelisk rises from the sands, forming the horn of a gargantuan Stone Rhinoceros Juggernaut", "the Lich will vomit forth She Who Rules Herself"],
        lich_seat_approach: ["she will speak through her Mummified feline (a Lion, a Cheetah, and a Smilodon) emissaries", "her conversation is pleasant, if a bit aloof. Happy to describe the time she bested The Horned Titan", "she may dismount, and invite the party to dine with her. She loves hearing descriptions of tastes and smells", "her ancient prejudices from a time of supreme matriarchy will mean she will only speak with females", "she may Geas the party to locate and re-secrete her phylactery. She doesn’t intend to allow them to survive with knowledge of it’s location however", "and offered sufficient tribute, she will cause the sky to blacken and pour torrential rains from the heavens", "she may solicit the party to deal with The Anchorite in exchange for arcane knowledge/services", "by a male, she may offer him vast treasures in change for a piece of his skeleton. She wishes to have a child."],
        hungry_sands_quicksand: ["was created by super-saturation. There’s an artesian spring here", "is a Fech fech, a layer of crust no thicker than a finger over pulverized clay", "consists of a layer of sand atop a thick and vicious pool of natural pitch", ", a three acre, eon-old Living Spell, curates an impressive underground museum of it’s victims. Untold treasures and secrets could be discovered within by risky and asphyxiating exploration"],
        hungry_sands_traverse: ["the nimble: one could gingerly hop across via strange lozenge-shaped stones. If only they were consistently spaced and all as sturdy as the first", "the hale: as it may entail holding one’s breath for an extended period of time", "the strong: bracing with ropes might be the safest way", "the clever: might notice a gangway of petrified planks, mostly covered in sand. No way to determine if they span the entire thing, or are sturdy enough to support more than a modest amount of weight, but it’s at least a start", "the wise: may simply go around, even if it adds a few days to the journey", "the socially careful: should try seeking advice from the Sidhe Bedouins, camped just outside of shout-shot. Their multicolored giraffes drink from tiny low clouds, while they enjoy their thick spiced coffee on rich carpets of spun sunlight"],
        hungry_sands_complication: ["are periodically patches of terra-firma, unfortunately festooned with thorny poisonous plants", "is an adventuring party on the opposite bank, traversing carefully", "seven greedy Ash Wights, that could potentially be placated with a toll", "is a skulk of Sand Scrags that wait in ambush just under the surface", "flails a hapless Bard, a Desert Tortoise Man who would rather die than lose", "is a scuttled Sandship, sparkling on it’s side. Retrofitted as a wonderworker’s laboratory it is leaking dangerous divine energy", "is a submerged Necropolis composed of the sand’s victims", "are a pair of Brass Dragons, mid-wedding who eye the party as guests/witnesses to their nuptials. Hope you brought presents."],
        horned_titan_legend: ["of his beautiful visage being forgotten (for he was quite vain), and had this massive sculpture commissioned as a form of immortality. A rival for his favorite courtesan's affections later added the horns", "once a benevolent Sultan who rules all these lands, he had himself frozen in time by powerful Elemental magics in order to return and save his people at some future time of strife", "by the Lich, a Medusa in life, she now sends her skeletal snake hair out to spy", "as punishment for the hubris of bringing man Fire from the Planes Infernal"],
        horned_titan_grass: ["serves as welcome fodder for pack animals of all types, a rarity in the desert", "is the result of recent localized rainfall, it’s lush but very temporary. You can", "crumbles under your footsteps, it too was transmuted to stone", "writhes and moans as it reaches for your feet", "has it’s frequent thirst quenched by periodic tears from the eyes of the Titan", "was cultivated with seeds straight from the bleak eternity of Gehenna. It thrives in the practically soaking conditions here. Hope it doesn’t spread via the"],
        horned_titan_village: ["a waystation for weary travelers, the Inn is a large, spacious yurt that can be had for three cups of water a night", "inhabited by the diminutive distant descendants of the Titan’s people", "was abandoned recently, and obviously in a hurry. Coals still smolder in the hearths and sorghum bread ovens and half-eaten food is on some tables", "and is a thriving Tiefling Colonizer outpost, full of xenophilic outcasts of all kinds, but almost too welcoming of strangers", "providing shelter for a strange hybrid Cult of Elemental Titan worshippers", "a basecamp for soon-to-begin expeditions into the nostrils and ears as Titan-bone prospectors hope to strike it rich", "houses a well-equipped Celestial Host, intent on launching crusades against the numerous Necropoli within the desert", "and within dwells a powerful Transmuter named Annathar and his extensive entourage of bungling apprentices. He’s researching a way to turn the stone to flesh"],
        oasis_visitors: ["a herd of skittish Oryx, drinking deeply in the shimmering desert heat", "a pandemonium of parrots, replete with vibrant plumage. They stop here on their annual migrations to the steamy jungles further south", "Jakongi the Bugbear Nomad patriarch and his extended family/tribe. Due to ancient custom, no bloodshed may be initiated at a water source and all travelers are offered hospitality. His curious cubs may prove a nuisance", "Ogre-sized sandblasted Brick Golems with the heads of rams and oxen, oblivious and impervious to almost everything, they ponderously fill beautiful decorated amphorae with water. If followed, they trek a few miles east, and dump their liquid cargo into an ancient cistern that nourishes an incredible Hanging Garden"],
        oasis_water: ["is crisp, cool, and refreshing but only accessible through a camel powered screw-pump that’s in need of repairs", "has recently been severely depleted by a travelling Camel Market", "will be rationed meticulously by the Water Genasi family who claim own-", "can only be retrieved by besting the local Water Weird in a spirited game", "connects directly with the Ocean via an Underground Sea and has been used by Merfolk as a trading hub for decades", "functions like a Fountain of Youth, halving the drinkers age with the first sip. Luckily, this wears off in about a day"],
        oasis_staying: ["is sorely tempting, if only to rest up from the journey", "may prove wise, as dark, ominous clouds gather to the west", "seems to be forbidden from the pictograms, glyphs, and warnings carved throughout every solid surface here", "will reveal new visitors (roll on table one again)", "could draw attention from the Thoul Mendicants that live nearby", "places the party directly in the path of an extravagant and moribund royal visit by a ghostly pharaonic entourage", "wouldn’t be so bad if it weren’t for the lonely and clingy Date Palm Dryads", "is made more comfortable by an enterprising business woman: Minasani. A Conjurer of no mean skill, her Sumptuous Inn spell provides a surprising"],
        sky_burial_corpse: ["serves as a potent warning: this Nomad died of dehydration. You eye your rapidly depleting water skins nervously", "one may discover, the religious trappings of Pilgrims, one of their num-", "reveals that this person was prematurely discounted as dead: a faint pulse is present. It is Dunmail the Dwarf an itinerant Ostrich Knight of modest", "is difficult due to it’s phantasmal nature, placed here with Permanence as a touching memento mori by a lovesick Illusionist"],
        sky_burial_offerings: ["is a Shroud of Protection from Scavengers and Vermin, fashioned from a hem of The Lich’s gown", "is an Axe of fine make and construction, highly enameled", "is an Axe of Dowsing, very useful in these parts", "is an Axe of Chromatic Dragon Friendship", "is an Axe of Amputation, severs limbs on critical hits", "are several sealed ceramic canopic jars, trapping different varieties of oozes and jellies instead of housing the deceased internal organs"],
        sky_burial_vultures: ["are quite large and vocal, but quickly flee to their nearby Yardang roosts", "possess magical feathers, that when fletched grant arrows the Undead Slaying property", "can speak, and as deeply religious Morticians, admonish the party to be respectful", "are the corpse’s many Animal Companions, guarding in death", "eat only coins and gemstones, they eye the parties money pouches hungrily", "have been known to summon terrific thunderstorms to strike down prey with lightning when carrion is scarce", "are quick to transform into one of their most advantageous, Desiccated Vampire forms (vampire, camel spider, vulture) and attack with the slightest provocation", "are sacred guardians, each with varied minor Draconic Heritage that grants them different kinds of breath weapons and plumage"],
        sandships_crew: ["cautious but friendly nomads who may or may not possess djinn-blood.", "fiercely matriarchal Dune Halfling outriggers and merchants with a wide-variety of frustratingly complex and arbitrary superstitions concerning sailing. Their daredevil natures can also be frightening at times", "Sirocco Elf pirates who plunder the numerous caravans that try to cross these parts with their Ogre Magi captain", "relict Ophidians from the empire which once stretched the length and breadth of the land. Their captain: Saurhothi, who is several centuries old, has never seen such large and strange hairless baboons"],
        sandships_fashioned_from: ["acacia planks, fastened together with joints and mortices. The sails are linen and heavily painted with wards against the evil eye", "hollowed saguaro, fashioned into catamarans. The sails are impossibly large leaves", "shiny, heavily etched brass that’s remarkably cool to the touch topped with enameled sails of thinly beaten tin", "translucent chartreuse glass, with snake-skin sails", "powerful pacts with elementals of Air and Earth", "portions of remarkably varied ships from different cultures and countries. Dreamlike, they shift forms whenever you look away. The whole effect is mildly disconcerting and leads to an unusual form of Sand-sea-sickness"],
        sandships_booking_passage: ["is quite dear, as the captain only accepts large gems and magical scrolls", "can be accomplished, as long as the destination is a Hex already visited", "is not strictly possible as they don’t take on passengers. Stowing away might be possible though before they weigh anchor", "may not be the best idea, legends tell of passengers boarding strange ships in the sands and never being heard from again", "will swiftly find you down in the galleys with the Orc oarsmen slaves", "involves complex transactions regarding hospitality at some indeterminate day, someday in the future the sailors will appear and require your assistance", "might be possible if you help them defeat the flight of Brown Dragon Wyrmlings harrying their ships", "seems like quite the bargain, until you realize that you’re being led straight toward She Who Rules Herself"],
        polyandrium_interred: ["are victims of a dormant but still deadly plague that wiped out an invading army by the Vector Of Disease, a legendary Anti-Paladin", "is the recently deceased Fire Giant war-chieftain Infarnox and his still smoldering Azer troops. This location insures that their corpses are never desecrated by loathsome water. It’s hot enough to melt lead here", "are the restless and Lawful Celestial Skeletal Soldiers that serve as a bulwark against the proliferation of the Necropoli. Waking them without cause would be unwise", "is every Dwarf to ever die in this desert, the Gods insure this and stock their military larders here for a massive pitched battle to provide them with entertainment after the end times"],
        polyandrium_maintained: ["infrequently, but there are small signs of tracks throughout", "never it would seem. This cemetery seems neglected and forgotten", "through the diligence and persistence of a small and dedicated family of overworked Scarab-Beetle Men", "by a chisel-tonsured order of elderly Gargoyles, under the auspices of the Godling of Bootless Deaths", "by the players for a week and a day, unless they are somehow able to resist the strong magical compulsions that radiate from this place", "or at least they were once maintained by Clockwork Bronze Automata in ceremonial armor. Lack of lubrication and the arid air has ground them all to a statuesque halt in the midst of various duties"],
        polyandrium_donation: ["casts Continual Light on a random item in their possession next time they find themselves in the dark", "may have to wait, as a kettle of Vulture-headed Aarakocra swoops down suddenly", "instantly fills water-skins with Holy Water", "instantly fills water-skins with Potions of Frenzy", "can be performed in a large stone bowl brimming with coins, guarded by a lethargic but lethal Stone Spitting Cobra", "will grant an automatic narrow success on the next failed task by the donor", "by non-martial types fills their dreams with bloody battles, interfering with sleep, but granting them a temporary bonus to melee attacks", "will improve the donors lowest ability score by 1"],
        sudden_sandstorm_storm: ["is thankfully short lived compared to some of the rumors you’ve heard. It lasts only about three hours", "proves to be particularly violent and brutal, at times composed of damaging sharp shards of stone", "could last as long as three days and nights, hunkering down and waiting it out might be your only option", "was conjured by the beating wings of a flock of Dire Rocs on take-off"],
        sudden_sandstorm_shelter: ["is the fortunate placement of caves within the rocky escarpment ahead, already occupied by some Gnoll Spice Merchants with similar ideas", "may be the gully you passed around an hour ago, if you can outpace the storm", "turns out to be a low mudbrick wall, not tall enough to provide protection for pack animals, but laying beside it might permit you to survive", "would probably that large rock up ahead, if it wasn’t an ornery Ankylosaurs", "seems like a long shot as visibility rapidly declines. Soon you can’t even see your own hand before your face. The leeward side of this large dune might be your only option, as suboptimal as that may be", "appears out of nowhere: a large, decadently embroidered pavilion tent, untroubled by the whipping wind. Sleeping inside is very restful, but you may find yourselves waking in a completely different part of the desert if the Cobra-Haired Medusa Meractama decides to let you live through the night"],
        sudden_sandstorm_aftermath: ["any nearby landmarks seem to have been erased or replaced", "you may discover that certain items have gone missing: swallowed forever by the sands in the panic", "the sands seem strewn with all manner of giant animal bones", "is an unburied cache of stoppered clay water pots, miraculously still full and unbroken", "cavort a mischievous score of Sand Mephits, still euphoric from the ride", "columns from a massive and utterly ancient temple complex are uncovered", "a nest of four Phoenix Eggs is uncovered", "bloom strange glass thistles, as far as the eye can see. Watered once a century by sandstorms such as this, they may be valuable, if exceedingly fragile"],
        necropolis_centered_on: ["a ruined desert village, formerly prosperous but now forever forgotten. The remains of 3d6 huts and hovels are scattered across 1d6 acres", "the trapped tomb of a significant personage from ages past, their Name lost to time. The site is 1d20x100 square feet in total and is buried beneath 1d6 feet of sand", "a toppled temple to bitter, evil deity, still seething for souls. 2d8x100 square feet in total area, with 8d4 columns", "a walled sandstone castle, positioned in a place of ancient strategic import. The silent guards that patrol the battlements no longer need rest. 2d6 Towers/Turrets, walls are 1d6+10 feet high, the fort is 1d6x100 feet wide at the narrowest point"],
        necropolis_undead: ["at least 20 normal Skeletons, led by a Wight. You were lucky this time.", "a war-band of 4d10 Skeletons that re-animate thrice, two turns after defeat", "2d20 Skeletons with ghostly mounts. They explode with negative energy", "Skeletal Knights (2d8), mounted on Mummified Wyverns", "2d6 Huecuva and half as many Wraiths that neutralize all divine magic", "a brilliant Specter Tactician directs his Skeleton Legions (1d4x100)"],
        necropolis_until: ["Holy Water (incredibly scarce in the desert) is sprinkled in a circle around the site", "the number exceeds 1,000, whereupon they march on the nearest settlement unless the entire area is Blessed by a Lawful Cleric", "something dead is mummified and entombed here according to esoteric rites that can be uncovered within", "the iron cauldron at the heart of the Necropolis is melted down and forged into horseshoes that are given to the poor", "a Hamsa is scrawled on the surface of every skull in the area", "the riddle of a Skeletal Sphinx at the center is solved", "the Mummified Maiden who dwells here is married", "The Lich’s phylactery, and thus the Lich herself are destroyed"],
        mirage_shows: ["the shuddering tops of distant date palms that always seem to grow near an oasis or wadi with plenty of water", "a long caravan of overladen camels, marching slowly to the left", "what could only be a large inland sea of some kind", "the shining gilt onion domes of a magnificent ivory colored palace"],
        mirage_trying_to_reach: ["will probably only waste several hours of travel and precious water", "could result in the party becoming almost hopelessly lost within the monotony of the desert", "may become more attractive over time, as it seems to re-appear whenever anyone rolls a 7", "is likely to cause the party to fall prey to a group of innovative Bandits who use a temperamental Rod Of Hallucinatory Terrain to mislead and then waylay their quarry", "will only draw you closer to the lair of the Blue Dragon, Merceleen", "might cause the part to stumble across a magnificent caldera, with an inside that glitters like a geode with sparkling purples. All arcane magic is significantly amplified within: it would make an ideal location for a wizard’s tower"],
        mirage_if: ["the entire party fasts for two days", "one turns around and walks in the opposite direction. Just a days travel that way", "everyone utters a prayer to The Lady of Visions", "you’ll visit it in your dreams", "prophetic dreams will provide it’s location", "and best the Sandman at storytelling", "you’ll wake up there", "anyone in the party dies in the next week. Should this occur, everyone will be instantaneously transported to an actual destination (as seen in the Mirage) whole and hale"],
        she_who_rules_size: ["just a little larger than a normal scorpion, about the size of a Halfling’s hand", "as wide as a Camel is tall, about the height of a Lion (tail not included)", "about as large as a Dragon", "big enough to house a village of Scorpionfolk worshippers on Her back, and could probably crush mountains with Her claws"],
        she_who_rules_venom: ["painfully transforms the victim into Scorpionfolk", "kills instantly, with no exceptions", "erases anything stung from existence itself", "has been used to commit deicide", "for She is just one of thousands of smaller ones, hibernating beneath the dunes, that wake should She feel threatened", "for She is the Primeval Goddess of all things that Sting"],
        she_who_rules_felled_by: ["drowning the book-lungs on Her belly", "being eaten by a Dire Roc, long thought to be extinct", "Her own venom", "a woman", "being trod upon by a Sciopod", "including a distant relative of one of the PCs, She will recognize their blood, and continually offer painful advice as to what their ancestor did wrong", "and she has crumbled empires, sages suggest that one must die from her sting seven times in seven lifetimes to slay her", "and countless more will still, for until the Great Desert is made lush and verdant, She Is."]
    },

    // --- EXPANDED ENCOUNTER LIST ---
    encounters: [
        "a lost merchant caravan", "a territorial Sand Worm", "a band of desert raiders", "a curious Djinni",
        "a pack of Hyenas", "a Blue Dragon", "a Giant Scorpion", "a company of Men, Nomads",
        "a wandering Mummy", "a Giant Ant Lion in its pit", "a flight of Giant Bats from a rocky outcrop",
        "a tribe of Goblins adapted to the heat", "a Gray Worm", "a Giant Tuatara Lizard",
        "a pack of Wraiths shimmering in the heat haze", "a nest of Giant Rattlers", "a herd of Camels",
        "a solitary, sun-bleached Skeleton that animates when approached"
    ],
    discoveries: [
        "a hidden oasis", "the sun-bleached skeleton of a massive desert creature", "a patch of hardy, but edible cacti",
        "ruins of an ancient city half-buried in sand", "a small, abandoned camp", "a series of strange, geometric patterns drawn in the sand",
        "a petrified forest", "the entrance to a buried tomb", "a dried-up well", "a singular, massive dune that seems to move on its own"
    ]
};